#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -eu

apt-get -y install -qq python-cheetah

install_java_tools() {
  apt-get -y install -qq openjdk-6-jdk maven gradle python-cheetah
}
install_java_tools


